### ISSUE TITLE
Exfile + exfile_imagemagick

### ISSUE THREAD

**Issue by noma4i** [keichan34/exfile-imagemagick#1]
I see issue with converting animated gif to any other format. For now it will produce files with zero length.

Maybe it's good idea to have a look on Arc package which has nice imagemagick implementation. W/o on the fly conversion which consumes a CPU like crazy on a page with ~100 images in a list.

**Comment by keichan34** [comment]
I'll check about animated gifs. It could be a problem with imagemagick.

In regards to on the fly conversion, that isn't going away anytime soon. You should put exfile behind a caching proxy or CDN to take care of that for you -- the URL should change when the image changes, so you don't have to worry about clearing the cache. If that doesn't work for you, I recommend using a different solution that stores the processing artifacts in some kind of storage for you, instead of processing on the fly.

**Comment by noma4i** [comment]
I will try to work out extension for Exfile to make conversion persistent.

Exfile is the one activly maintained project for file uploads in phoenix.
Thats why Im interested in using   and contributing to it.

## 

Alex T
